# Generated by Django 4.0 on 2023-03-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_comment_product_product_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('image', models.ImageField(default='default.jpeg', null=True, upload_to='profile')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('commen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment_Product',
        ),
    ]
