# Generated by Django 4.0 on 2023-03-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_comment_delete_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
